version: 0
metadata:
  name: "TaskCluster GitHub Tests"
  description: "Tests for taskcluster github in production"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - release
    payload:
      maxRunTime: 3600
      image: "node:5"
      command:
        - "/bin/bash"
        - "-lc"
        - "echo 'This works! (From a Release!)'"
    metadata:
      name: "TaskCluster GitHub Tests from a Release"
      description: "Tests for taskcluster github in production/staging (from a release)"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
